export const surpriseMePrompts = [
  'A celestial jellyfish floating through a nebula-filled sky, rendered as a mesmerizing 3D animation',
  'A cosmic carousel with planets and stars as its horses, transformed into an ukiyo-e woodblock print',
  'A psychedelic astronaut riding a comet like a surfboard, captured in a vibrant lomography-style photograph',
  'A kaleidoscopic black hole swirling with vibrant colors, depicted as a digital art masterpiece',
  'A constellation of fireflies creating patterns in the night sky, reimagined as a surreal oil painting',
  'A moonlit forest with trees made of swirling galaxies, captured in a stunning long-exposure photograph',
  'A time-traveling spaceship leaving trails of stardust, portrayed as a futuristic 3D render',
  'An intergalactic dance party on a moonlit asteroid, transformed into a cosmic graffiti mural',
  'A trippy dreamscape with planets as stepping stones across a cosmic river, brought to life through digital painting',
  'A surreal cosmic carnival with alien performers and neon lights, rendered as an otherworldly holographic installation',
  'A cosmic butterfly fluttering through a field of glittering stars, portrayed in a dreamy watercolor painting',
  'A space cat riding a rainbow beam between galaxies, captured as a playful digital illustration',
  'A cosmic symphony of planets and stars playing musical instruments, depicted in an intricate tapestry',
  'A psychedelic wormhole leading to a parallel universe, brought to life through an immersive virtual reality experience',
  'An alien cityscape illuminated by bioluminescent plants and neon signs, captured in a mesmerizing long-exposure photograph',
  'A neon-colored spaceship racing through an electrifying space tunnel, depicted as a futuristic 3D render',
  'A swirling vortex of colors and shapes in deep space, transformed into a hypnotic animated GIF',
  'A cosmic painter creating galaxies with every brushstroke, portrayed in a vibrant abstract expressionist painting',
  'An otherworldly tea party on a floating asteroid, reimagined as an intricate diorama',
  'A sunflower field in space, each sunflower a glowing star, captured in a celestial 3D render',
  'A constellation of interstellar beings forming patterns in the sky, depicted in a cosmic stained glass window',
  'A psychedelic space serpent weaving through a starry sky, transformed into a mesmerizing digital fractal',
  'A celestial wizard conjuring galaxies with cosmic spells, portrayed in an enchanting fantasy illustration',
  'A cosmic aquarium with fish made of swirling galaxies and stardust, brought to life through a captivating holographic sculpture',
  'A hypnotic spiral galaxy spinning in the night sky, captured in a breathtaking long-exposure photograph',
  'A floating island in space with waterfalls of stardust, depicted as a serene lomography-style snapshot',
  'An alien DJ spinning records under a cosmic disco ball, reimagined as a futuristic digital art installation',
  'A cosmic cathedral with stained glass windows of galaxies and stars, transformed into an ethereal 3D render',
  'A trippy space-time vortex bending reality and perception, portrayed in a mind-bending optical illusion artwork',
  'An astronaut surfing on a rainbow wave through the cosmos, captured in a dynamic digital animation',
  'A planetary dance party with orbiting disco balls and laser lights, reimagined as a futuristic music festival poster',
  'A cosmic owl soaring through constellations with wings of stardust, brought to life through an intricate wood carving',
  'A space station with gardens growing in zero gravity, depicted in a whimsical 3D diorama',
  'A psychedelic supernova exploding in a burst of color and light, transformed into a mesmerizing abstract painting',
  'A cosmic butterfly effect causing ripples across galaxies, captured in an otherworldly holographic sculpture',
  'A celestial library with books made of swirling nebulae and star clusters, depicted as an ancient illuminated manuscript',
  'A talking cactus wearing a sombrero and playing the accordion at a desert party, captured in a lively lomography-style photograph.',
  'A group of penguins sunbathing on a tropical beach, sipping coconut drinks with tiny umbrellas, depicted as an ukiyo-e woodblock print.',
  'A squirrel mafia conducting a secret meeting in a tree hollow, wearing fedoras and holding miniature briefcases, transformed into an intricate diorama.',
  'An octopus cooking a gourmet underwater feast with an assortment of seafood ingredients, portrayed in a detailed oil painting.',
  'A T-Rex riding a unicycle while juggling flamingos in a circus tent, reimagined as a mesmerizing 3D render.',
  'A hipster walrus sporting a handlebar mustache and round glasses, enjoying a latte in a coffee shop underwater, captured in a quirky digital illustration.',
  'A UFO landing in a farm field, surrounded by curious cows taking selfies with aliens, brought to life through a futuristic holographic sculpture.',
  'A ninja cat stealthily sneaking into a museum to steal a famous painting of a mouse, transformed into an enigmatic lomography-style snapshot.',
  'A wizard rabbit casting spells to grow a magical carrot garden, depicted in a whimsical watercolor painting.',
  'A disco ballroom filled with dancing flamingos in groovy 1970s outfits and afro wigs, portrayed as a neon-lit digital art installation.',
  'A sleepy sloth directing a blockbuster movie set in a high-speed race, complete with race cars and explosions, transformed into a dynamic animation.',
  'A polar bear hosting a karaoke night for seals and penguins on an iceberg stage, captured in a playful 3D render.',
  'A vampire hummingbird sipping tiny drops of blood from flower petals at twilight, portrayed in a dramatic oil painting.',
  'A giraffe playing the saxophone in a jazz band with other animal musicians, depicted as a lively 3D diorama.',
  'A chameleon fashion show featuring reptiles dressed in vibrant, color-changing couture, transformed into an intricate fabric collage.',
  'A space kangaroo exploring the cosmos in a rocket-powered pouch, portrayed in a captivating digital painting.',
  'A futuristic robot teapot serving tea to a group of curious alien creatures, brought to life through an imaginative 3D render.',
  'A group of garden gnomes having a wild pool party in a hidden backyard oasis, captured in a whimsical lomography-style photograph.',
  'A superhero snail donning a cape and mask, zooming to the rescue at a snails pace, portrayed as a comic book cover.',
  'A painterly portrait of a time-traveling squirrel riding a penny-farthing bicycle through various historical eras, depicted in a stunning oil painting.'
];